export const CATEGORIES = [
  { name: "Programming Fundamentals" },
  { name: "Web Development" },
  { name: "Mobile Development" },
  { name: "Game Development" },
  { name: "Data Structures & Algorithms" },
  { name: "Databases & SQL" },
  { name: "DevOps & Cloud Computing" },
  { name: "Cybersecurity" },
  { name: "Artificial Intelligence & Machine Learning" },
  { name: "Data Science & Analytics" },
  { name: "Computer Vision" },
  { name: "Natural Language Processing" },
  { name: "Operating Systems" },
  { name: "Computer Networks" },
  { name: "Software Engineering & Architecture" },
  { name: "Functional Programming" },
  { name: "Systems Programming" },
  { name: "Embedded Systems & IoT" },
  { name: "Blockchain & Web3" },
  { name: "Programming Languages" },
  { name: "Testing & Quality Assurance" },
  { name: "API Development & Integration" },
  { name: "UI/UX Design for Developers" },
  { name: "Competitive Programming" },
  { name: "High-Performance Computing" },
  { name: "Parallel & Distributed Systems" },
];
