import "./globals.css";
import type { Metadata } from "next";
import { MuiCacheProvider } from "@/components/providers/mui-cache-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { roboto } from "@/lib/fonts";
import { SessionProvider } from "@/components/providers/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={roboto.variable}>
          <MuiCacheProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </MuiCacheProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
